### ISSUE TITLE
QNAP docker

### ISSUE THREAD

**Issue by Magic73** [LucianoZu/mydockers#2]
Ciao Luciano,
ho installato il docker sul mio QNAP. Ho avviato il docker, ma amule sembra che non sia in esecuzione.
Non riesco ad accedervi via browser sulla 4711. Amule parte in automatico, all'avvio del docker?

Da terminale del docker, se avvio "amule" mi torna errore:

AdunanzA says: bye bye!                                                                                                                                  
Error: Unable to initialize gtk, is DISPLAY set properly?  

Puoi aiutarmi? non sono pratico di docker.. e sembra l'unico modo per usare amule adunanza su Qnap.

**Comment by LucianoZu** [comment]
Ciao,

dunque io uso il docker sul mio desktop. In genere organizzo i miei docker
in modo tale che possa lanciare gli applicativi in un secondo momento e non
quando viene fatto docker run.

Quindi preparo degli script che mi aiutino in questo. Prima di tutto devi
lanciare 12_run.sh per creare il container. Fatto questo puoi entrarci
dentro in bash digitando 30_connect.sh oppure lanciare adunanza come
applicazione desktop con 35_adunanza.sh

La seconda volta che hai bisogno di far partire il container non far
partire lo script di run ma solo quello di start.

Per funzionare adunanza hai bisogno di montare (come è indicato in
12_run.sh) la parte grafica del tuo server.

Spero ti sia stato d'aiuto. Se poi vuoi lanciare il tutto come servizio ti
consiglio di usare la 30_connect.sh e capire quale comando devi lanciare
per far partire tutto come headless.

Luciano


   - Profilo LinkedIn: http://www.linkedin.com/in/lucianozu
   - Ardulink: http://www.ardulink.org/
   - Lucio Caio Autore: http://luciocaio.altervista.org/





Il giorno gio 6 dic 2018 alle ore 16:05 Magic73 <notifications@github.com>
ha scritto:

**Comment by Magic73** [comment]
Intanto grazie, sia per il docker che per la pronta risposta.

Su QNAP, non credo di poter avviare docker con anche la grafica. Ad ogni modo, in teoria, Amule Adunanza dovrebbe avere anche il demone web (quello che sta in ascolto sulla 4711 e che ti permette di controllare amule da un qualunque browser).

Cmq, ho installato il docker tramite docker hub. dal qnap, avvio il container… e mi ritrovo con la console bash. (non ho modo di avviare alcun che di grafico).

la bash mi posizione nella cartella /home/adunanza dell'utente adunanza.

da qua, dove trovo gli script di cui parli?

**Comment by LucianoZu** [comment]
Ok,

gli script sono sul repo git. Sono script che vanno lanciati dalla macchina
host non dal container e servono a farlo partire, a stopparlo,a riavviarlo,
a connettersi in bash al container (quello che hai fatto tu) o volendo a
far partire adunanza GUI.

Allora se sei riuscito ad arrivare con la bash dentro il container devi
semplicemente trovare il modo per far partire il servizio web. Con il
comando amule fai partire la parte grafica.

Luciano


   - Profilo LinkedIn: http://www.linkedin.com/in/lucianozu
   - Ardulink: http://www.ardulink.org/
   - Lucio Caio Autore: http://luciocaio.altervista.org/





Il giorno gio 6 dic 2018 alle ore 17:57 Magic73 <notifications@github.com>
ha scritto:
